# Generated by Django 2.1.5 on 2019-03-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='techonlogy',
        ),
        migrations.AddField(
            model_name='post',
            name='postTechnology',
            field=models.CharField(choices=[('wt', 'wt'), ('android', 'android'), ('ios', 'ios'), ('java', 'java'), ('python', 'python')], default='wt', max_length=10),
        ),
    ]
