# Generated by Django 2.1.5 on 2019-02-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='phnone',
            new_name='phone',
        ),
    ]
