# Generated by Django 2.1.5 on 2019-02-23 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=200)),
                ('lastName', models.CharField(default='', max_length=200)),
                ('enrollmentNumber', models.CharField(default='', max_length=20)),
                ('picture', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('wtMarks', models.SmallIntegerField(default='0')),
                ('androidMarks', models.SmallIntegerField(default='0')),
                ('iosMarks', models.SmallIntegerField(default='0')),
                ('javaMarks', models.SmallIntegerField(default='0')),
                ('pythonMarks', models.SmallIntegerField(default='0')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
