# Generated by Django 2.1.5 on 2019-03-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190223_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profileCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
