# Generated by Django 2.1.5 on 2019-03-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190322_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cpi',
            field=models.FloatField(default='0'),
        ),
    ]
